os: osx
language: cpp
compiler: clang

env:
  global:
    - TCI_DIR_TEMP=$HOME/Downloads
    - TCI_DIR_DEPS=$HOME/Thirdparty
    - TCI_DIR_APPS=$HOME/Bundles
  matrix:
    - TCI_USE_TILES=yes
    - TCI_USE_TILES=no

cache:
  ccache: true
  directories:
    - $HOME/Thirdparty

before_install:
  - brew update
  - brew install gettext lua
  - brew link --force gettext
  - TCI_URLS=(
      'http://libsdl.org/release/SDL2-2.0.8.dmg'
      'https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.3.dmg'
      'https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.2.dmg'
      'https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.dmg'
    )
  - TCI_INCR=2
  - |
    mkdir -p "$TCI_DIR_DEPS"
    if [[ "$TCI_USE_TILES" == yes ]] \
        && [[ "$TCI_INCR:${#TCI_URLS[@]}" != "$(< "$TCI_DIR_DEPS/vers")" ]]
    then
      rm -rf "$TCI_DIR_DEPS" && mkdir "$TCI_DIR_DEPS"
      mkdir -p $TCI_DIR_TEMP
      pushd $TCI_DIR_TEMP
      for url in "${TCI_URLS[@]}"; do
        curl -LO --fail --retry 5 $url
        hdiutil mount -readonly -mountpoint sdl *.dmg
        cp -R sdl/*.framework "$TCI_DIR_DEPS"
        hdiutil unmount sdl
        rm *.dmg
      done
      popd
      echo "$TCI_INCR:${#TCI_URLS[@]}" > "$TCI_DIR_DEPS/vers"
    fi

script:
  - |
    mkdir -p $TCI_DIR_APPS
    if [[ "$TCI_USE_TILES" == yes ]]; then
      TCI_MAKE_OPTIONS=(-j2 RELEASE=1 USE_HOME_DIR=1 NATIVE=osx OSX_MIN=10.7 CLANG=1 CACHE=1 USE_LIBCXX=1 LTO=1 LOCALIZE=1 LANGUAGES=all LUA=1 TILES=1 SOUND=1 FRAMEWORK=1 FRAMEWORKSDIR="$TCI_DIR_DEPS")
      make "${TCI_MAKE_OPTIONS[@]}"
      make "${TCI_MAKE_OPTIONS[@]}" app
      zip -9 -r --symlinks $TCI_DIR_APPS/CataclysmDDA-Mac-Graphics-$TRAVIS_TAG.zip *.app
      openssl dgst -sha512 $TCI_DIR_APPS/*.zip | tee $TCI_DIR_APPS/Checksum-Graphics-$TRAVIS_TAG.sha512.txt
    else
      TCI_MAKE_OPTIONS=(-j2 RELEASE=1 USE_HOME_DIR=1 NATIVE=osx OSX_MIN=10.7 CLANG=1 CACHE=1 USE_LIBCXX=1 LTO=1 LOCALIZE=1 LANGUAGES=all LUA=1)
      make "${TCI_MAKE_OPTIONS[@]}"
      make "${TCI_MAKE_OPTIONS[@]}" app
      zip -9 -r --symlinks $TCI_DIR_APPS/CataclysmDDA-Mac-Terminal-$TRAVIS_TAG.zip *.app
      openssl dgst -sha512 $TCI_DIR_APPS/*.zip | tee $TCI_DIR_APPS/Checksum-Terminal-$TRAVIS_TAG.sha512.txt
    fi

deploy:
  skip_cleanup: true
  file_glob: true
  file: $TCI_DIR_APPS/*
  provider: releases
  api_key:
    secure: MSkUY30Aqtxj7c5CY7qTre3X99OFwqRu4+6eOOHvp7EdQHUf7iY4qg6vD8vpw0cUAf4XAZ73jG+OQh7wntM3YfsYihXHHBjhXQMG1PQA096ynrXsDP1EFiM98nTJ4fawzjo/1/n0FCk5ZXXi3tPXePF0ytKLIu3KP1uCoJAWklUGO0PKmjjevy590047YVSI1lQZkqC1J7cNS+654mSWO3GWWJAWigzprM8cqBQSdXW2uV3snt3ARc6vV7PKX3qrKYMpHLhxO2aFX55DhT4MZS4hEvhMjQKbuf/kbF1EmLG1GakCgHOnj/twhlV7vVr6/hPYVAkSP4vFv0axTZcf90KHitkEwk3Ecb4E0N1EXgDt7vPKaraeFkXIncoCvOa3413DX99SV1FKiWyqyK7vFREcXjHToFvXRE5wGAuHjJ6RWdJ3tQnucDr3LpzSDEOqGkVLs0xjANvS3XbhBPZviMNTUoPLIQ38q3A4xoFRmr2dXzOrpVZW4/QKdQY4HN1RPf7G5pMI39PIEjmJK2LQpP7q3yk013gSRV05XKjPGF/Sos5lERdFsy87+lhIq1FQqJHLjDxb9dV1tNe0r3FrznqXOkQSuG1XK+cqivJ9j2K1a6Zm6uLCrkfdYJ/mA5YoCXGUrO94iAEECSu65PW/v0BdUdditi3Hs3wKakBPWKo=
  on:
    repo: auto-load/Cataclysm-DDA
    tags: true
    branch: osx

notifications:
  irc:
    channels:
      - 'irc.freenode.org#CataclysmDDA'
    template:
      - '%{repository}#%{build_number}: New personal experimental build for OS X :P (https://github.com/%{repository_slug}/releases/)'
    on_success: always
    on_failure: never
    use_notice: true
    skip_join: true
